using System.Collections.Concurrent;
using System.ComponentModel;
using System.Text;
using Microsoft.Extensions.AI;

using AzureFinOps.Dashboard.Infrastructure;

namespace AzureFinOps.Dashboard.AI.Tools;

/// <summary>
/// Generates downloadable Azure CLI / PowerShell scripts from FinOps recommendations.
/// The LLM produces the script content after discussing with the user, and this tool
/// packages it as a downloadable .ps1 or .sh file with a code preview in the UI.
/// </summary>
public static class ScriptTools
{
    // Store generated files for download: fileId → (path, created, content)
    internal static readonly ConcurrentDictionary<string, (string Path, DateTime Created, string Content)> GeneratedFiles = new();

    internal static void CleanupOldFiles() =>
        TempFileHelper.CleanupOldFiles(GeneratedFiles, v => v.Created, v => v.Path);

    public static IEnumerable<AIFunction> Create()
    {
        yield return AIFunctionFactory.Create(GenerateScript, "GenerateScript",
            @"Generates a downloadable Azure CLI or PowerShell script from FinOps recommendations.

Call ONLY AFTER you have analyzed the user's environment, found actionable recommendations (orphaned resources, untagged, right-sizing, idle VMs, unattached disks, missing budgets, etc.) AND confirmed the user wants a script.

If no actionable recommendations yet, do NOT call this tool. Tell the user: 'I don't have actionable recommendations to script yet — let me first analyze your environment.'

Script MUST include safety features: --what-if / confirmation prompts / dry-run mode, comments per logical step. Prefer Azure CLI (`az`) unless user asks for PowerShell.");
    }

    private static Task<string> GenerateScript(
        [Description(@"The full script content (Azure CLI or PowerShell). Must include:
- A header comment block explaining what the script does, prerequisites, and usage
- Safety features: dry-run mode, confirmation prompts, or --what-if flags
- Clear comments for each logical section
- Error handling for critical operations
Example header:
#!/bin/bash
# FinOps Remediation Script: Delete Orphaned Disks
# Generated by Azure FinOps Agent
# Prerequisites: Azure CLI 2.50+, logged in via 'az login'
# Usage: chmod +x script.sh && ./script.sh
# Mode: DRY-RUN by default — set DRY_RUN=false to execute")] string scriptContent,
        [Description("Filename for the script (without extension). Default: 'finops-remediation'")] string? filename,
        [Description("Script language: 'bash' for .sh (Azure CLI), 'powershell' for .ps1. Default: 'bash'")] string? language,
        [Description("Brief description of what the script does (shown in the UI download button)")] string? description)
    {
        if (string.IsNullOrWhiteSpace(scriptContent))
            return Task.FromResult("Error: No script content provided.");

        CleanupOldFiles();

        var lang = (language ?? "bash").ToLowerInvariant();
        var ext = lang == "powershell" ? ".ps1" : ".sh";
        var fileId = Guid.NewGuid().ToString("N")[..12];
        var safeName = string.IsNullOrWhiteSpace(filename) ? "finops-remediation" : SanitizeFilename(filename);
        var outputPath = Path.Combine(Path.GetTempPath(), $"{fileId}_{safeName}{ext}");
        var desc = string.IsNullOrWhiteSpace(description) ? "FinOps remediation script" : description;

        File.WriteAllText(outputPath, scriptContent, Encoding.UTF8);

        GeneratedFiles[fileId] = (outputPath, DateTime.UtcNow, scriptContent);

        var lineCount = scriptContent.Split('\n').Length;

        return Task.FromResult($"__SCRIPT_READY__:{fileId}:{safeName}{ext}:{lineCount}:{lang}:{desc}");
    }

    private static string SanitizeFilename(string name) =>
        TempFileHelper.SanitizeFilename(name, "finops-remediation");
}
